function [TOT_P_ALL, DIR_ALL,TOT_P_ALL_BACK_UP, DIR_ALL_BACK_UP] = updateLaneLikelihoods(NBUFFER, PROB_KEY, DIR_KEY, PROB_KEY_BACK_UP, TOT_P_ALL, DIR_ALL,TOT_P_ALL_BACK_UP, DIR_ALL_BACK_UP )

 TOT_P_ALL(:,:,1:NBUFFER-1) = TOT_P_ALL(:,:,2:NBUFFER);
 TOT_P_ALL(:,:,NBUFFER)     = PROB_KEY;
 
 DIR_ALL(:,:,1:NBUFFER-1)   = DIR_ALL(:,:,2:NBUFFER);
 DIR_ALL(:,:,NBUFFER)       = DIR_KEY;

 TOT_P_ALL_BACK_UP(:,:,1:NBUFFER-1) = TOT_P_ALL_BACK_UP(:,:,2:NBUFFER);
 TOT_P_ALL_BACK_UP(:,:,NBUFFER)     = PROB_KEY_BACK_UP;
            
 DIR_ALL_BACK_UP(:,:,1:NBUFFER-1)   = DIR_ALL_BACK_UP(:,:,2:NBUFFER);
 DIR_ALL_BACK_UP(:,:,NBUFFER)       = DIR_KEY;


end